blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls'))
]

blog/blogs/urls.py
"""Определяет схемы URL для blogs."""

from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    path('blogs/', views.blogs, name='blogs'),
    path('blogs/<int:blog_id>/', views.blog, name='blog'),
    path('new_blog/', views.new_blog, name='new_blog'),
    path('new_post/<int:blog_id>/', views.new_post, name='new_post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

blog/users/urls.py
""" Определяет схемы URL для пользователей. """
from django.urls import path, include
from . import views
app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации.
    path('register/', views.register, name='register'),
]

blog/blogs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Blog(models.Model):
    """Blog model."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a human readable representation of the model object."""
        return self.name


class BlogPost(models.Model):
    """Blog post model."""
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    title = models.CharField(max_length=500)
    text = models.TextField()
    date_added = models.DateField(auto_now_add=False)

    def __str__(self):
        """Return a string representing the blog post."""
        return f"{self.title[:50]}..."

blog/users/models.py
from django.db import models

# Create your models here.

blog/blogs/forms.py
from django import forms
from .models import Blog, BlogPost


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['name']
        labels = {'name': ''}


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost

        fields = ['title', 'text', 'date_added']
        labels = {'title': 'Title', 'text': 'Text', 'date_added': 'Date Added'}
        widgets = {'text': forms.Textarea(
            attrs={'cols': 80}), 'date_added': forms.DateInput(attrs={'type': 'date'})}

blog/blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Blog, BlogPost
from .forms import BlogForm, BlogPostForm
# Create your views here.


def index(request):
    """Домашняя страница приложения Blog"""
    return render(request, 'blogs/index.html')


@login_required
def blogs(request):
    """Выводит список тем."""
    blogs = Blog.objects.filter(owner=request.user).order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)


@login_required
def blog(request, blog_id):
    """Выводит одну тему и все ее записи."""
    blog = Blog.objects.get(id=blog_id)
    if blog.owner != request.user:
        raise Http404
    posts = blog.blogpost_set.all()
    context = {'blog': blog, 'posts': posts}
    return render(request, 'blogs/blog.html', context)


@login_required
def new_blog(request):
    """Определяет новую тему."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = BlogForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return redirect('blogs:blogs')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)


@login_required
def new_post(request, blog_id):
    """Добавляет новую запись по конкретной теме."""
    blog = Blog.objects.get(id=blog_id)
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = BlogPostForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.blog = blog
            new_post.save()
            return redirect('blogs:blog', blog_id=blog_id)
    # Вывести пустую или недействительную форму.
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_post.html', context)


@login_required
def edit_post(request, post_id):
    """Редактирует существующую запись."""
    post = BlogPost.objects.get(id=post_id)
    blog = post.blog
    if blog.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = BlogPostForm(instance=post)
    else:
        # Отправка данных POST; обработать данные.
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog', blog_id=blog.id)
    context = {'post': post, 'blog': blog, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

blog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            login(request, new_user)
            return redirect('blogs:index')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blog/blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Blog</title>
	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}
</head>
<body>
<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
	<a class="navbar-brand" href="{% url 'blogs:index' %}">
		Blog</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse"
			data-target="#navbarCollapse" aria-controls="navbarCollapse"
			aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span></button>
	<div class="collapse navbar-collapse" id="navbarCollapse">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'blogs:blogs' %}">
					Blogs</a></li>
		</ul>
		<ul class="navbar-nav ml-auto">
			{% if user.is_authenticated %}
				<li class="nav-item">
					<span class="navbar-text"> Hello, {{ user.username }}.</span>
				</li>
				<li class="nav-item">
					<form action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-light">log out</button>
                    </form>
				</li>
			{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:register' %}">Register</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
			{% endif %}
		</ul>
	</div>
</nav>
<main role="main" class="container">
	<div class="pb-2 mb-2 border-bottom">
		{% block page_header %}{% endblock page_header %}
	</div>
	<div>
		{% block content %}{% endblock content %}
	</div>
</main>
</body>
</html>

blog/blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}
{% block content %}
  <p>Blog: {{ blog }}</p>
  <p>Posts:</p>
  <p>
    <a href="{% url 'blogs:new_post' blog.id %}">add new post</a>
  </p>
  <ul>
  {% for post in posts %}
    <li>
      <p>{{ post.title }}</p>
      <p>{{ post.date_added|date:'M d, Y' }}</p>
      <p>{{ post.text|linebreaks }}</p>
      <p>
        <a href="{% url 'blogs:edit_post' post.id %}">Edit post</a>
      </p>
    </li>
  {% empty %}
    <li>This blog does not have any posts yet¯\_(ツ)_/¯</li>
  {% endfor %}
  </ul>
{% endblock content %}

blog/blogs/templates/blogs/blogs.html
{% extends "blogs/base.html" %}
{% block content %}
  <p>Blogs</p>
  <ul>
    {% for blog in blogs %}
    <li>
        <a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a>
    </li>
    {% empty %}
      <li>No blogs ¯\_(ツ)_/¯</li>
    {% endfor %}
  </ul>
  <a href="{% url 'blogs:new_blog' %}">Add a new blog:</a>
{% endblock content %}

blog/blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% block content %}
	<p><a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a></p>
	<p>Edit entry:</p>
		<form action="{% url 'blogs:edit_post' post.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">save changes</button>
	</form>
{% endblock content %}

blog/blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}
{% block content %}
    <p>Blog helps you!</p>
{% endblock content %}

blog/blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% block content %}

	<p>Add a new blog:</p>
	<form action="{% url 'blogs:new_blog' %}" method='post'>
	{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">add blog</button>
	</form>

{% endblock content %}

blog/blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% block content %}
  <p><a href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a></p>
  <p>Add a new post:</p>
  <form action="{% url 'blogs:new_post' blog.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>add post</button>
  </form>
{% endblock content %}